export const games = [
  // MASTER SYSTEM
  {
    id: 'sms-sonic',
    nome: 'Sonic The Hedgehog',
    console: 'MASTER SYSTEM',
    core: 'smsplus',
    rom_url: '/sonicthehedgehog.sms',
    capa_url:
      'https://upload.wikimedia.org/wikipedia/en/b/ba/Sonic_the_Hedgehog_1_Genesis_box_art.jpg',
  },
  {
    id: 'sms-alex-kidd',
    nome: 'Alex Kidd in Miracle World',
    console: 'MASTER SYSTEM',
    core: 'smsplus',
    rom_url: '/alexkidd.sms',
    capa_url: '/alexkidd.jpg',
  },

  // SNES
  {
    id: 'snes-aladdin',
    nome: "Disney's Aladdin",
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/aladdin.sfc',
    capa_url: '/aladdin.jpg',
  },
  {
    id: 'snes-batman-forever',
    nome: 'Batman Forever',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/batman-forever.sfc',
    capa_url: '/batman-forever.jpg',
  },
  {
    id: 'snes-battletoads',
    nome: 'Battletoads',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/battletoads.sfc',
    capa_url: '/battletoads.jpg',
  },
  {
    id: 'snes-battletoads-dd',
    nome: 'Battletoads & Double Dragon',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/battletoads-double-dragon.sfc',
    capa_url: '/battletoads-double-dragon.jpg',
  },
  {
    id: 'snes-chrono-trigger',
    nome: 'Chrono Trigger',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/chrono-trigger.sfc',
    capa_url: '/chrono-trigger.jpg',
  },
  {
    id: 'snes-contra3',
    nome: 'Contra III',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/contra-3.sfc',
    capa_url: '/contra-3.jpg',
  },
  {
    id: 'snes-dkc',
    nome: 'Donkey Kong Country',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/dkc.sfc',
    capa_url: '/dkc.png',
  },
  {
    id: 'snes-fatal-fury2',
    nome: 'Fatal Fury 2',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/fatal-fury-2.sfc',
    capa_url: '/fatal-fury-2.jpg',
  },
  {
    id: 'snes-goof-troop',
    nome: 'Goof Troop',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/goof-troop.sfc',
    capa_url: '/goof-troop.jpg',
  },
  {
    id: 'snes-harvest-moon',
    nome: 'Harvest Moon',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/harvest-moon.sfc',
    capa_url: '/harvest-moon.jpg',
  },
  {
    id: 'snes-kirbys-avalanche',
    nome: "Kirby's Avalanche",
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/kirbys-avalanche.sfc',
    capa_url: '/kirbys-avalanche.jpg',
  },
  {
    id: 'snes-kirby-super-star',
    nome: 'Kirby Super Star',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/kirby-super-star.sfc',
    capa_url: '/kirby-super-star.jpg',
  },
  {
    id: 'snes-megaman-x',
    nome: 'Mega Man X',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/megaman-x.sfc',
    capa_url: '/megaman-x.jpg',
  },
  {
    id: 'snes-megaman-x2',
    nome: 'Mega Man X2',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/megaman-x2.sfc',
    capa_url: '/megaman-x2.jpg',
  },
  {
    id: 'snes-megaman-x3',
    nome: 'Mega Man X3',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/megaman-x3.sfc',
    capa_url: '/megaman-x3.jpg',
  },
  {
    id: 'snes-rrr',
    nome: "Rock n' Roll Racing",
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/rrr.sfc',
    capa_url: '/rrr.jpg',
  },
  {
    id: 'snes-supermarioworld',
    nome: 'Super Mario World',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/supermarioworld.sfc',
    capa_url:
      'https://upload.wikimedia.org/wikipedia/en/3/32/Super_Mario_World_Coverart.png',
  },
  {
    id: 'snes-topgear',
    nome: 'Top Gear',
    console: 'SNES',
    core: 'snes9x',
    rom_url: '/topgear.smc',
    capa_url: '/Capa_de_Top_Gear.jpg',
  },

  // NES
  {
    id: 'nes-contra',
    nome: 'Contra',
    console: 'NES',
    core: 'nestopia',
    rom_url: '/contra.nes',
    capa_url: '/contra.jpg',
  },
  {
    id: 'nes-duck-hunt',
    nome: 'Duck Hunt',
    console: 'NES',
    core: 'nestopia',
    rom_url: '/duck-hunt.nes',
    capa_url: '/duck-hunt.jpg',
  },

  // GBA
  {
    id: 'gba-zelda-minish-cap',
    nome: 'The Legend of Zelda: The Minish Cap',
    console: 'GBA',
    core: 'mgba',
    rom_url: '/LegendOfZeldaTheMinishCap.gba',
    capa_url: '/zelda.jpg',
  },
  {
    id: 'gba-pokemon-fire-red',
    nome: 'Pokémon Fire Red',
    console: 'GBA',
    core: 'mgba',
    rom_url: '/pokemon-fire-red.gba',
    capa_url: '/pokemon-fire-red.jpg',
  },

  // GAME BOY
  {
    id: 'gb-pokemon-silver',
    nome: 'Pokémon Silver',
    console: 'GAME BOY',
    core: 'gambatte',
    rom_url: '/PokémonSilver.gbc',
    capa_url: '/pokemon-silver.jpg',
  },

  // N64
  {
    id: 'n64-super-mario-64',
    nome: 'Super Mario 64',
    console: 'NINTENDO 64',
    core: 'mupen64plus_next',
    rom_url: '/Super_Mario_64.z64',
    capa_url: '/Super_Mario_64.jpg',
  },

  // ATARI
  {
    id: 'atari-asteroids',
    nome: 'Asteroids',
    console: 'ATARI',
    core: 'stella',
    rom_url: '/asteroids.a26',
    capa_url: '/asteroids.jpg',
  },
];

export const gamesDb = {
  // MASTER SYSTEM
  'sms-sonic': {
    id: 'sms-sonic',
    rom_url: '/sonicthehedgehog.sms',
    core: 'smsplus',
    nome: 'Sonic The Hedgehog',
    ano: '1991',
    fabricante: 'SEGA',
    capa_url: '/sonicthehedgehog.jpg',
    descricao: 'A estreia do ouriço mais rápido do mundo no Master System!',
  },
  'sms-alex-kidd': {
    id: 'sms-alex-kidd',
    rom_url: '/alexkidd.sms',
    core: 'smsplus',
    nome: 'Alex Kidd in Miracle World',
    ano: '1986',
    fabricante: 'SEGA',
    capa_url: '/alexkidd.jpg',
    descricao: 'O maior clássico do Master System! Use o Jokenpô para vencer!',
  },

  // SNES
  'snes-aladdin': {
    id: 'snes-aladdin',
    rom_url: '/aladdin.sfc',
    core: 'snes9x',
    nome: "Disney's Aladdin",
    ano: '1993',
    fabricante: 'Capcom',
    capa_url: '/aladdin.jpg',
    descricao: 'A versão clássica da Capcom baseada no filme da Disney.',
  },
  'snes-batman-forever': {
    id: 'snes-batman-forever',
    rom_url: '/batman-forever.sfc',
    core: 'snes9x',
    nome: 'Batman Forever',
    ano: '1995',
    fabricante: 'Acclaim',
    capa_url: '/batman-forever.jpg',
    descricao: 'Batman enfrenta Two-Face e Arlequina no filme de 1995.',
  },
  'snes-battletoads': {
    id: 'snes-battletoads',
    rom_url: '/battletoads.sfc',
    core: 'snes9x',
    nome: 'Battletoads',
    ano: '1994',
    fabricante: 'Rare',
    capa_url: '/battletoads.jpg',
    descricao: 'Rash, Zitz e Pimple enfrentam a Dark Queen!',
  },
  'snes-battletoads-dd': {
    id: 'snes-battletoads-dd',
    rom_url: '/battletoads-double-dragon.sfc',
    core: 'snes9x',
    nome: 'Battletoads & Double Dragon',
    ano: '1993',
    fabricante: 'Rare/Technos',
    capa_url: '/battletoads-double-dragon.jpg',
    descricao: 'Toads e Double Dragon unem forças contra Shadow Boss!',
  },
  'snes-chrono-trigger': {
    id: 'snes-chrono-trigger',
    rom_url: '/chrono-trigger.sfc',
    core: 'snes9x',
    nome: 'Chrono Trigger',
    ano: '1995',
    fabricante: 'Square',
    capa_url: '/chrono-trigger.jpg',
    descricao: 'Uma das maiores aventuras RPG de todos os tempos!',
  },
  'snes-contra3': {
    id: 'snes-contra3',
    rom_url: '/contra-3.sfc',
    core: 'snes9x',
    nome: 'Contra III: The Alien Wars',
    ano: '1992',
    fabricante: 'Konami',
    capa_url: '/contra-3.jpg',
    descricao: 'A maior aventura dos Contra Brothers no futuro!',
  },
  'snes-dkc': {
    id: 'snes-dkc',
    rom_url: '/dkc.sfc',
    core: 'snes9x',
    nome: 'Donkey Kong Country',
    ano: '1994',
    fabricante: 'Rare/Nintendo',
    capa_url: '/dkc.jpg',
    descricao: 'Donkey e Diddy em uma aventura revolucionária em 3D!',
  },
  'snes-fatal-fury2': {
    id: 'snes-fatal-fury2',
    rom_url: '/fatal-fury-2.sfc',
    core: 'snes9x',
    nome: 'Fatal Fury 2',
    ano: '1992',
    fabricante: 'SNK',
    capa_url: '/fatal-fury-2.jpg',
    descricao: 'Terry Bogard e cia no torneio do Rei das Trevas!',
  },
  'snes-goof-troop': {
    id: 'snes-goof-troop',
    rom_url: '/goof-troop.sfc',
    core: 'snes9x',
    nome: 'Goof Troop',
    ano: '1993',
    fabricante: 'Capcom/Disney',
    capa_url: '/goof-troop.jpg',
    descricao: 'Max e PJ salvam o Prefeito X com truques malucos!',
  },
  'snes-harvest-moon': {
    id: 'snes-harvest-moon',
    rom_url: '/harvest-moon.sfc',
    core: 'snes9x',
    nome: 'Harvest Moon',
    ano: '1996',
    fabricante: 'Natsume',
    capa_url: '/harvest-moon.jpg',
    descricao: 'Reconstrua a fazenda e encontre o amor verdadeiro!',
  },
  'snes-kirbys-avalanche': {
    id: 'snes-kirbys-avalanche',
    rom_url: '/kirbys-avalanche.sfc',
    core: 'snes9x',
    nome: "Kirby's Avalanche",
    ano: '1995',
    fabricante: 'HAL',
    capa_url: '/kirbys-avalanche.jpg',
    descricao: 'Kirby no puzzle game estilo Puyo Puyo!',
  },
  'snes-kirby-super-star': {
    id: 'snes-kirby-super-star',
    rom_url: '/kirby-super-star.sfc',
    core: 'snes9x',
    nome: 'Kirby Super Star',
    ano: '1996',
    fabricante: 'HAL/Nintendo',
    capa_url: '/kirby-super-star.jpg',
    descricao: 'Múltiplas aventuras do Kirby rosa e faminto!',
  },
  'snes-megaman-x': {
    id: 'snes-megaman-x',
    rom_url: '/megaman-x.sfc',
    core: 'snes9x',
    nome: 'Mega Man X',
    ano: '1993',
    fabricante: 'Capcom',
    capa_url: '/megaman-x.jpg',
    descricao: 'O futuro dos Mavericks começa aqui com X!',
  },
  'snes-megaman-x2': {
    id: 'snes-megaman-x2',
    rom_url: '/megaman-x2.sfc',
    core: 'snes9x',
    nome: 'Mega Man X2',
    ano: '1994',
    fabricante: 'Capcom',
    capa_url: '/megaman-x2.jpg',
    descricao: 'Wire Sponge, Wheel Gator e mais 6 Mavericks!',
  },
  'snes-megaman-x3': {
    id: 'snes-megaman-x3',
    rom_url: '/megaman-x3.sfc',
    core: 'snes9x',
    nome: 'Mega Man X3',
    ano: '1995',
    fabricante: 'Capcom',
    capa_url: '/megaman-x3.jpg',
    descricao: 'O último grande X do SNES com escolhas morais!',
  },
  'snes-rrr': {
    id: 'snes-rrr',
    rom_url: '/rrr.sfc',
    core: 'snes9x',
    nome: "Rock n' Roll Racing",
    ano: '1993',
    fabricante: 'Blizzard',
    capa_url: '/rrr.jpg',
    descricao: 'Acelere ao som de rock em corridas intergalácticas!',
  },
  'snes-supermarioworld': {
    id: 'snes-supermarioworld',
    rom_url: '/supermarioworld.sfc',
    core: 'snes9x',
    nome: 'Super Mario World',
    ano: '1990',
    fabricante: 'Nintendo',
    capa_url: '/supermarioworld.jpg',
    descricao: 'O clássico absoluto que definiu o SNES!',
  },
  'snes-topgear': {
    id: 'snes-topgear',
    rom_url: '/topgear.smc',
    core: 'snes9x',
    nome: 'Top Gear',
    ano: '1992',
    fabricante: 'Kemco/Gremlin',
    capa_url: '/Capa_de_Top_Gear.jpg',
    descricao: 'O jogo de corrida mais amado do Brasil!',
  },

  // NES
  'nes-contra': {
    id: 'nes-contra',
    rom_url: '/contra.nes',
    core: 'nestopia',
    nome: 'Contra',
    ano: '1987',
    fabricante: 'Konami',
    capa_url: '/contra.jpg',
    descricao: 'Bill Rizer e Lance Bean contra os aliens!',
  },
  'nes-duck-hunt': {
    id: 'nes-duck-hunt',
    rom_url: '/duck-hunt.nes',
    core: 'nestopia',
    nome: 'Duck Hunt',
    ano: '1984',
    fabricante: 'Nintendo',
    capa_url: '/duck-hunt.jpg',
    descricao: 'O cão zoeiro e sua Zapper na caça aos patos!',
  },

  // GBA
  'gba-zelda-minish-cap': {
    id: 'gba-zelda-minish-cap',
    rom_url: '/LegendOfZeldaTheMinishCap.gba',
    core: 'mgba',
    nome: 'The Legend of Zelda: The Minish Cap',
    ano: '2004',
    fabricante: 'Capcom/Nintendo',
    capa_url: '/zelda.jpg',
    descricao: 'Link encolhe com Ezlo para salvar Hyrule!',
  },
  'gba-pokemon-fire-red': {
    id: 'gba-pokemon-fire-red',
    rom_url: '/pokemon-fire-red.gba',
    core: 'mgba',
    nome: 'Pokémon Fire Red',
    ano: '2004',
    fabricante: 'Game Freak',
    capa_url: '/pokemon-fire-red.jpg',
    descricao: 'Kanto em 3D com Pokémon até a Geração III!',
  },

  // GAME BOY
  'gb-pokemon-silver': {
    id: 'gb-pokemon-silver',
    rom_url: '/PokémonSilver.gbc',
    core: 'gambatte',
    nome: 'Pokémon Silver',
    ano: '1999',
    fabricante: 'Game Freak',
    capa_url: '/pokemon-silver.jpg',
    descricao: 'Gold e Silver na região de Johto e Kanto!',
  },

  // N64
  'n64-super-mario-64': {
    id: 'n64-super-mario-64',
    rom_url: '/Super_Mario_64.z64',
    core: 'mupen64plus_next',
    nome: 'Super Mario 64',
    ano: '1996',
    fabricante: 'Nintendo',
    capa_url: '/Super_Mario_64.jpg',
    descricao: 'A revolução 3D que mudou os games para sempre!',
  },

  // ATARI
  'atari-asteroids': {
    id: 'atari-asteroids',
    rom_url: '/asteroids.a26',
    core: 'stella',
    nome: 'Asteroids',
    ano: '1979',
    fabricante: 'Atari',
    capa_url: '/asteroids.jpg',
    descricao: 'O clássico arcade que definiu os shoot em up!',
  },
};